name: reqres
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  get_it: ^7.6.7
  go_router: ^13.2.0
  google_fonts: ^4.0.3
  http: ^1.2.0
  flutter_svg: ^2.0.4
  image_picker: ^1.1.2
  image: ^3.0.1
  textfield_tags: ^3.0.1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon/eye_show.svg
    - assets/icon/eye_hidden.svg
    - assets/icon/eye_hidden.png
    - assets/icon/eye_show.png
    - assets/icon/edit.svg
    - assets/icon/add.svg
    - assets/icon/hororscope.svg
    - assets/icon/zodiac.svg
